generate:
  - types
  - client
accessModifier: internal
additionalFileComments:
  - "swift-format-ignore-file"
  - "swiftlint:disable all"
filter:
  operations:
    - "repos/get"
    - "search/repos"
namingStrategy: idiomatic
